"""
Multi-agent implementation using the supervisor pattern.

    ┌─────────────┐
    │  supervisor  │  (LLM) decides which specialist handles the next step
    └──────┬───────┘
     ┌─────┼──────────────┐
     ▼     ▼              ▼
 research  math        writing
  agent    agent        agent
     │     │              │
     └─────┴──────────────┘
           back to supervisor, repeat until done

The supervisor is itself an LLM with "handoff tools" (one per worker,
auto-generated by `create_supervisor`). Calling a handoff tool transfers
control -- and the full message history -- to that worker. The worker
runs its own ReAct loop, then control returns to the supervisor, which
decides the next step or ends the conversation.

This is the recommended pattern from `langgraph-supervisor` for
"several distinct specialists + one orchestrator that stays in control"
(as opposed to peer-to-peer "handoff" architectures where agents talk
directly to the user).
"""

from langgraph.checkpoint.memory import InMemorySaver
from langgraph_supervisor import create_supervisor

from src.config import get_llm
from src.agents.research_agent import build_research_agent
from src.agents.math_agent import build_math_agent
from src.agents.writing_agent import build_writing_agent

SUPERVISOR_PROMPT = """You are a supervisor coordinating three specialists:

- research_agent: looks things up on the web, returns facts + sources.
- math_agent: performs any arithmetic/calculations.
- writing_agent: turns gathered facts/numbers into a polished final answer.

Route work to exactly the specialist(s) needed for the user's request, in
whatever order makes sense. Do not do research, math, or writing yourself --
always delegate. Once you have everything needed, delegate a final pass to
writing_agent so the user gets one clean answer, then stop."""


def build_supervisor_app():
    """
    Returns a compiled multi-agent graph ready to `.invoke()`.
    """
    supervisor_llm = get_llm(temperature=0.1)

    research_agent = build_research_agent()
    math_agent = build_math_agent()
    writing_agent = build_writing_agent()

    checkpointer = InMemorySaver()

    workflow = create_supervisor(
        agents=[research_agent, math_agent, writing_agent],
        model=supervisor_llm,
        prompt=SUPERVISOR_PROMPT,
    )

    app = workflow.compile(checkpointer=checkpointer)
    return app
